MSEloss_depth: false
SmmothL1loss_depth: true
ac_func:
- true
- true
- false
batch_size: 32
best_model: null
ckp_dir: /root/sensor-fusion-gesture/pretrain_ckp/results0
ckpt_term: 100
config_num: 0
cuda_id: 0
dataset: synthetic
dataset_dir: /root/Dataset/synthetic/001
depth_loss_weight: 1
drop_prob:
- 0.5
- 0.5
- 0
expr_ID: test1
fitting: true
iter: false
j2d_loss_weight: 0
j3d_loss_weight: 0
lr: 0.0001
lr_decay_gamma: 0.1
lr_decay_step: 1
lr_reduce: false
manual_seed: 24657
momentum: 0.9
n_epochs: 10
normalize: false
num_fclayers:
- 2087
- 512
- 512
- 39
num_iter: 3
num_workers: 4
optimizer: adam
params_loss_weight: 1
pred_scale: false
pretrained: false
reg_loss_weight: 1
to_mano: null
try_num: 0
use_dropout:
- true
- true
- false
use_multigpu: true
weight_decay: 1.0e-05
